### ISSUE TITLE
Invalid Clock speed information

### ISSUE THREAD

**Issue by srevrtt** [Pigiotyreal/Winfetch#1]
When I run the program on Windows (.\winfetch.exe, powershell), I get invalid CPU clock speed information. 
![image](https://user-images.githubusercontent.com/94027678/230388659-ea7ddb72-e847-4237-a3c6-517e475cebfb.png).

According to Windows, my clock speed is actually 2.90GHz.
![image](https://user-images.githubusercontent.com/94027678/230389083-0fc11d87-60d5-4771-9290-ace03aceb37e.png)

**Comment by Aznos** [comment]
Issue should be fixed, can you confirm this?

**Comment by srevrtt** [comment]
It works now.
